import { useMemo, useState } from 'react'
import { BarChart3, Building2, FileSignature, KeyRound, Link2, ReceiptText, Send, Stethoscope, Languages, Smartphone, UserRound } from 'lucide-react'
import { usePrototypeData } from '../context/PrototypeDataContext'
import { useToast } from '../context/ToastContext'

const tabs = [
  ['Client Portal', Building2], ['Doctor Portal', Stethoscope], ['Patient Portal', UserRound], ['Interpreter Management', Languages],
  ['Billing & Invoices', ReceiptText], ['Secure Report Delivery', Send], ['Advanced Analytics', BarChart3], ['Mobile Views', Smartphone],
  ['Integration Settings', Link2], ['API Management', KeyRound], ['Electronic Signatures', FileSignature],
] as const
const field='w-full border border-slate-200 rounded-lg px-3 py-2 text-sm text-slate-700 focus:outline-none focus:ring-2 focus:ring-brand-500/30 focus:border-brand-500'
const card='bg-white border border-slate-200 rounded-xl p-4'

export default function Advanced(){
  const {clients,doctors,cases,appointments,reports}=usePrototypeData(); const {showToast}=useToast();
  const [tab,setTab]=useState<(typeof tabs)[number][0]>('Client Portal')
  const [interpreterName,setInterpreterName]=useState(''); const [interpreters,setInterpreters]=useState([{id:'INT-01',name:'Sofia Rossi',languages:'Italian, English',availability:'Available'}])
  const [invoices,setInvoices]=useState([{id:'INV-2026-104',client:clients[0]?.name??'Client',amount:'£850.00',status:'Draft'}])
  const [deliveryReport,setDeliveryReport]=useState(reports[0]?.id??''); const [recipient,setRecipient]=useState(''); const [expiry,setExpiry]=useState('2026-09-14')
  const [integration,setIntegration]=useState({email:true,calendar:true,storage:false,identity:true}); const [apiKeys,setApiKeys]=useState([{id:'KEY-01',name:'Reporting integration',created:'07 Sep 2026',status:'Active'}])
  const [signatures,setSignatures]=useState([{id:'SIG-01',report:reports[0]?.id??'Report',signer:doctors[0]?.name??'Doctor',status:'Pending'}])
  const activeCases=cases.filter(c=>!['Completed','Cancelled','Archived'].includes(c.status)); const completed=cases.filter(c=>c.status==='Completed').length
  const portalCases=useMemo(()=>activeCases.slice(0,5),[activeCases])
  const sectionTitle=(title:string,desc:string)=><div className="mb-4"><h2 className="text-sm font-semibold text-slate-900">{title}</h2><p className="text-xs text-slate-500 mt-1">{desc}</p></div>
  return <div className="space-y-4 max-w-[1500px] mx-auto">
    <div><h1 className="text-lg font-semibold text-slate-900">Advanced features</h1><p className="text-xs text-slate-500 mt-1">Tab 3 Priority 3 screens represented as functional front-end prototype workflows.</p></div>
    <div className="flex gap-1 overflow-x-auto border-b border-slate-200">{tabs.map(([name,Icon])=><button key={name} onClick={()=>setTab(name)} className={`inline-flex items-center gap-1.5 px-3 py-2 text-xs font-medium border-b-2 whitespace-nowrap ${tab===name?'border-brand-600 text-brand-700':'border-transparent text-slate-500 hover:text-slate-700'}`}><Icon size={13}/>{name}</button>)}</div>

    {tab==='Client Portal'&&<div className={card}>{sectionTitle('Client Portal','Permission-controlled external view for instructing organisations.')}<div className="overflow-x-auto"><table className="w-full text-sm"><thead className="text-[11px] uppercase tracking-wide text-slate-400 bg-slate-50"><tr><th className="text-left p-2">Client</th><th className="text-left p-2">Active cases</th><th className="text-left p-2">Delivery preference</th><th className="text-left p-2">Portal access</th></tr></thead><tbody className="divide-y divide-slate-100">{clients.map(c=><tr key={c.id}><td className="p-2 font-medium text-slate-700">{c.name}</td><td className="p-2 text-slate-500">{activeCases.filter(x=>x.client===c.name).length}</td><td className="p-2 text-slate-500">{c.reportDeliveryPreference}</td><td className="p-2"><button onClick={()=>showToast(`Client portal invitation prepared for ${c.name}.`)} className="text-xs font-medium text-brand-600">Invite / manage access</button></td></tr>)}</tbody></table></div></div>}

    {tab==='Doctor Portal'&&<div className="grid lg:grid-cols-2 gap-4"><div className={card}>{sectionTitle('Doctor Portal','External expert view for appointments, assigned cases, documents and report actions.')}<div className="space-y-2">{doctors.map(d=><div key={d.id} className="border border-slate-100 rounded-lg p-3 flex justify-between gap-3"><div><p className="text-sm font-medium text-slate-800">{d.name}</p><p className="text-xs text-slate-500 mt-1">{activeCases.filter(c=>c.doctor===d.name).length} active cases · {appointments.filter(a=>a.doctor===d.name&&a.status==='Scheduled').length} appointments</p></div><button onClick={()=>showToast(`Doctor portal access reviewed for ${d.name}.`)} className="text-xs font-medium text-brand-600">Manage access</button></div>)}</div></div><div className={card}>{sectionTitle('Portal work queue','Cases visible to the selected medical expert according to assignment permissions.')}<div className="space-y-2">{portalCases.map(c=><div key={c.ref} className="rounded-lg bg-slate-50 border border-slate-100 p-3"><p className="text-sm font-medium text-slate-800">{c.ref} · {c.patient}</p><p className="text-xs text-slate-500 mt-1">{c.doctor} · {c.status}</p></div>)}</div></div></div>}

    {tab==='Patient Portal'&&<div className={card}>{sectionTitle('Patient Portal','Patient-facing appointment status, secure messages and permitted documents only.')}<div className="grid md:grid-cols-3 gap-3">{appointments.slice(0,6).map(a=><div key={a.id} className="rounded-lg border border-slate-100 p-3"><p className="text-sm font-medium text-slate-800">{a.patient}</p><p className="text-xs text-slate-500 mt-1">{a.date} · {a.time}</p><p className="text-xs text-slate-400 mt-1">{a.location} · {a.status}</p><button onClick={()=>showToast(`Patient portal notification queued for ${a.patient}.`)} className="mt-3 text-xs font-medium text-brand-600">Send portal update</button></div>)}</div></div>}

    {tab==='Interpreter Management'&&<div className="grid lg:grid-cols-[360px_minmax(0,1fr)] gap-4"><div className={card}>{sectionTitle('Add interpreter','Maintain language capability and availability.')}<label className="text-xs text-slate-500">Name *</label><input className={`${field} mt-1`} value={interpreterName} onChange={e=>setInterpreterName(e.target.value)} placeholder="Interpreter name"/><button disabled={!interpreterName.trim()} onClick={()=>{setInterpreters(v=>[{id:`INT-${Date.now()}`,name:interpreterName.trim(),languages:'English + language to confirm',availability:'Available'},...v]);setInterpreterName('');showToast('Interpreter added.')}} className="mt-3 px-3 py-2 text-xs font-medium bg-brand-600 text-white rounded-lg disabled:opacity-40">Add interpreter</button></div><div className={card}>{sectionTitle('Interpreter directory','Availability can be checked during appointment scheduling.')}<div className="space-y-2">{interpreters.map(i=><div key={i.id} className="border border-slate-100 rounded-lg p-3 flex justify-between"><div><p className="text-sm font-medium text-slate-800">{i.name}</p><p className="text-xs text-slate-500">{i.languages}</p></div><span className="text-xs text-emerald-700">{i.availability}</span></div>)}</div></div></div>}

    {tab==='Billing & Invoices'&&<div className={card}>{sectionTitle('Billing and Invoice Management','Track case-related commercial records separately from clinical content.')}<button onClick={()=>setInvoices(v=>[{id:`INV-2026-${100+v.length+1}`,client:clients[v.length%Math.max(1,clients.length)]?.name??'Client',amount:'£850.00',status:'Draft'},...v])} className="mb-3 px-3 py-2 text-xs font-medium bg-brand-600 text-white rounded-lg">Create invoice</button><div className="space-y-2">{invoices.map(i=><div key={i.id} className="border border-slate-100 rounded-lg p-3 flex justify-between gap-3"><div><p className="text-sm font-medium text-slate-800">{i.id}</p><p className="text-xs text-slate-500">{i.client} · {i.amount}</p></div><button onClick={()=>setInvoices(v=>v.map(x=>x.id===i.id?{...x,status:x.status==='Draft'?'Issued':'Paid'}:x))} className="text-xs font-medium text-brand-600">{i.status} → advance</button></div>)}</div></div>}

    {tab==='Secure Report Delivery'&&<div className={card}>{sectionTitle('Secure External Report Delivery','Create a permission-controlled delivery record with expiry and recipient confirmation.')}<div className="grid md:grid-cols-3 gap-3"><div><label className="text-xs text-slate-500">Final report</label><select className={`${field} mt-1`} value={deliveryReport} onChange={e=>setDeliveryReport(e.target.value)}>{reports.map(r=><option key={r.id} value={r.id}>{r.caseRef} · {r.reportType}</option>)}</select></div><div><label className="text-xs text-slate-500">Recipient *</label><input className={`${field} mt-1`} value={recipient} onChange={e=>setRecipient(e.target.value)} placeholder="recipient@example.com"/></div><div><label className="text-xs text-slate-500">Access expiry</label><input type="date" className={`${field} mt-1`} value={expiry} onChange={e=>setExpiry(e.target.value)}/></div></div><button disabled={!recipient.trim()} onClick={()=>showToast(`Secure delivery link created for ${recipient}; expires ${expiry}.`)} className="mt-4 px-3 py-2 text-xs font-medium bg-brand-600 text-white rounded-lg disabled:opacity-40">Create secure delivery</button></div>}

    {tab==='Advanced Analytics'&&<div className="space-y-4"><div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-3"><Metric label="Active cases" value={activeCases.length}/><Metric label="Completed cases" value={completed}/><Metric label="Reports delivered" value={reports.filter(r=>r.status==='Delivered').length}/><Metric label="Appointments completed" value={appointments.filter(a=>a.status==='Completed').length}/></div><div className={card}>{sectionTitle('Advanced analytics filters','Cross-module analysis by period, client, doctor and workflow status.')}<div className="grid md:grid-cols-4 gap-3"><input type="date" className={field} defaultValue="2026-08-01"/><input type="date" className={field} defaultValue="2026-09-07"/><select className={field}><option>All clients</option>{clients.map(c=><option key={c.id}>{c.name}</option>)}</select><select className={field}><option>All doctors</option>{doctors.map(d=><option key={d.id}>{d.name}</option>)}</select></div></div></div>}

    {tab==='Mobile Views'&&<div className={card}>{sectionTitle('Mobile-Responsive Views','Responsive navigation and workflow screens are available for reduced-width devices.')}<div className="max-w-sm mx-auto border-[8px] border-slate-800 rounded-[2rem] p-3 bg-slate-50 min-h-96"><div className="bg-white rounded-xl border border-slate-200 p-3"><p className="text-xs font-semibold text-slate-800">Evaluate Medicolegal</p><p className="text-[11px] text-slate-400 mt-1">Mobile case summary</p><div className="space-y-2 mt-4">{portalCases.slice(0,4).map(c=><div key={c.ref} className="rounded-lg border border-slate-100 p-2"><p className="text-xs font-medium">{c.ref}</p><p className="text-[11px] text-slate-500">{c.patient} · {c.status}</p></div>)}</div></div></div></div>}

    {tab==='Integration Settings'&&<div className={card}>{sectionTitle('Integration Settings','Configure external services without exposing credentials in the operational UI.')}<div className="space-y-3">{Object.entries(integration).map(([key,value])=><label key={key} className="flex items-center justify-between border border-slate-100 rounded-lg p-3"><div><p className="text-sm font-medium text-slate-800 capitalize">{key} integration</p><p className="text-xs text-slate-400">Connection and permission settings</p></div><input type="checkbox" checked={value} onChange={e=>setIntegration(prev=>({...prev,[key]:e.target.checked}))}/></label>)}</div></div>}

    {tab==='API Management'&&<div className={card}>{sectionTitle('API Management','Issue and revoke prototype API credentials for authorised integrations.')}<button onClick={()=>setApiKeys(v=>[{id:`KEY-${Date.now()}`,name:`Integration key ${v.length+1}`,created:'07 Sep 2026',status:'Active'},...v])} className="mb-3 px-3 py-2 text-xs font-medium bg-brand-600 text-white rounded-lg">Create API key</button><div className="space-y-2">{apiKeys.map(k=><div key={k.id} className="border border-slate-100 rounded-lg p-3 flex justify-between"><div><p className="text-sm font-medium text-slate-800">{k.name}</p><p className="text-xs text-slate-500">{k.id} · Created {k.created}</p></div><button onClick={()=>setApiKeys(v=>v.map(x=>x.id===k.id?{...x,status:'Revoked'}:x))} className="text-xs font-medium text-red-600">{k.status==='Active'?'Revoke':'Revoked'}</button></div>)}</div></div>}

    {tab==='Electronic Signatures'&&<div className={card}>{sectionTitle('Electronic Signatures','Track report signature requests and completion status.')}<button onClick={()=>setSignatures(v=>[{id:`SIG-${Date.now()}`,report:reports[v.length%Math.max(1,reports.length)]?.id??'Report',signer:doctors[v.length%Math.max(1,doctors.length)]?.name??'Doctor',status:'Pending'},...v])} className="mb-3 px-3 py-2 text-xs font-medium bg-brand-600 text-white rounded-lg">Create signature request</button><div className="space-y-2">{signatures.map(sig=><div key={sig.id} className="border border-slate-100 rounded-lg p-3 flex justify-between"><div><p className="text-sm font-medium text-slate-800">{sig.report}</p><p className="text-xs text-slate-500">Signer: {sig.signer}</p></div><button onClick={()=>setSignatures(v=>v.map(x=>x.id===sig.id?{...x,status:'Signed'}:x))} className="text-xs font-medium text-brand-600">{sig.status}</button></div>)}</div></div>}
  </div>
}

function Metric({label,value}:{label:string;value:string|number}){return <div className="bg-white border border-slate-200 rounded-xl p-4"><p className="text-[11px] uppercase tracking-wide text-slate-400">{label}</p><p className="text-2xl font-semibold text-slate-900 mt-2">{value}</p></div>}
