import { useState } from 'react'
import { Link } from 'react-router-dom'
import { ArrowRight } from 'lucide-react'
import StatusBadge from '../components/StatusBadge'
import PageToolbar from '../components/PageToolbar'
import NewClientModal from '../components/NewClientModal'
import { useTableFilter } from '../hooks/useTableFilter'
import { usePrototypeData } from '../context/PrototypeDataContext'

export default function Clients() {
  const { clients, addClient } = usePrototypeData()
  const [modalOpen,setModalOpen]=useState(false)
  const {search,setSearch,filterDefs,activeFilters,toggleFilter,clearFilters,activeFilterCount,filtered,dateRange,setDateRange,dateFilterAvailable,tableSortOptions,activeTableSort,setActiveTableSort}=useTableFilter(clients,['name','primaryContact','email'],[{key:'type',label:'Client type',options:[...new Set(clients.map(c=>c.type))]},{key:'status',label:'Status',options:['Active','Inactive']}])
  return <div className="space-y-4"><PageToolbar searchPlaceholder="Search clients by organisation or contact..." searchValue={search} onSearchChange={setSearch} resultCount={filtered.length} actionLabel="Create client" onAction={()=>setModalOpen(true)} filterDefs={filterDefs} activeFilters={activeFilters} onToggleFilter={toggleFilter} onClearFilters={clearFilters} activeFilterCount={activeFilterCount} dateRange={dateRange} onDateRangeChange={setDateRange} dateFilterAvailable={dateFilterAvailable} sortOptions={tableSortOptions} activeSort={activeTableSort} onSortChange={setActiveTableSort}/><div className="bg-white rounded-xl border border-slate-200 overflow-hidden"><div className="px-4 py-3 border-b border-slate-100"><h2 className="text-sm font-semibold text-slate-900">Clients</h2><p className="text-xs text-slate-400 mt-0.5">Organisation contacts, workload and recent activity.</p></div><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="bg-slate-50 text-left text-[11px] text-slate-500 uppercase tracking-wide"><th className="px-4 py-2.5 font-medium">Client</th><th className="px-4 py-2.5 font-medium">Type</th><th className="px-4 py-2.5 font-medium">Primary contact</th><th className="px-4 py-2.5 font-medium">Cases</th><th className="px-4 py-2.5 font-medium">Last activity</th><th className="px-4 py-2.5 font-medium">Status</th><th className="px-4 py-2.5 font-medium text-right">Action</th></tr></thead><tbody className="divide-y divide-slate-100">{filtered.map(c=><tr key={c.id} className="hover:bg-slate-50"><td className="px-4 py-3"><Link to={`/clients/${c.id}`} className="font-semibold text-brand-600 hover:text-brand-700">{c.name}</Link><p className="text-[11px] text-slate-400 mt-0.5">{c.id}</p></td><td className="px-4 py-3 text-xs text-slate-600">{c.type}</td><td className="px-4 py-3"><p className="text-xs font-medium text-slate-700">{c.primaryContact}</p><p className="text-[11px] text-slate-400 mt-0.5">{c.email}</p></td><td className="px-4 py-3"><p className="text-xs text-slate-700">{c.activeCases} active</p><p className="text-[11px] text-slate-400 mt-0.5">{c.completedCases} completed</p></td><td className="px-4 py-3 text-xs text-slate-500">{c.lastActivity}</td><td className="px-4 py-3"><StatusBadge status={c.status}/></td><td className="px-4 py-3 text-right"><Link to={`/clients/${c.id}`} className="inline-flex items-center gap-1 text-xs font-medium text-brand-600">Open <ArrowRight size={13}/></Link></td></tr>)}{filtered.length===0&&<tr><td colSpan={7} className="px-4 py-9 text-center text-slate-400 text-sm">No clients match the current search or filters.</td></tr>}</tbody></table></div></div>{modalOpen&&<NewClientModal existingCount={clients.length} onClose={()=>setModalOpen(false)} onCreate={c=>{addClient(c);setModalOpen(false)}}/>}</div>
}
