import { useMemo, useState } from 'react'
import { CheckCircle2, FileText, Pencil, Plus, Power, Upload } from 'lucide-react'
import Modal from './Modal'
import { useToast } from '../context/ToastContext'
import { ALL_CASE_STATUSES, ALLOWED_CASE_TRANSITIONS } from '../utils/caseWorkflow'

const field = 'w-full border border-slate-200 rounded-lg px-3 py-2 text-sm bg-white text-slate-700 focus:outline-none focus:ring-2 focus:ring-brand-500/30 focus:border-brand-500'
const label = 'block text-[11px] font-semibold text-slate-500 mb-1.5'

type CaseStatusRule = { id:string; name:string; order:number; active:boolean; allowedNext:string; rolePermissions:string; requiredFields:string; completionRules:string }
type AppointmentTypeRule = { id:string; name:string; duration:number; locationType:string; doctorEligibility:string; interpreterSupport:boolean; active:boolean }
type DocumentCategoryRule = { id:string; name:string; order:number; requirement:'Required'|'Optional'|'Generated'; aiRules:string; active:boolean }
type ReportTemplate = { id:string; name:string; reportType:string; client:string; caseType:string; version:number; status:'Active'|'Inactive'; lastUpdated:string; fileName:string }
type Checklist = { id:string; name:string; reportType:string; items:string[]; requiredItems:string[]; severityOptions:string[]; active:boolean }

const statusMeta:Record<string,{roles:string;required:string;completion:string}>={
  'New Booking':{roles:'Booking Administrator, Operations Manager',required:'Patient, instruction source',completion:'Booking details validated'},
  'Information Required':{roles:'Booking Administrator, Operations Manager',required:'Missing information reason',completion:'Required information received'},
  'Booking Confirmed':{roles:'Booking Administrator, Operations Manager',required:'Patient, client/direct instruction, assigned doctor',completion:'Booking confirmed'},
  'Appointment Pending':{roles:'Booking Administrator, Operations Manager',required:'Assigned doctor, appointment requirement',completion:'Appointment scheduled or confirmed not required'},
  'Appointment Scheduled':{roles:'Booking Administrator, Operations Manager, Medical Expert',required:'Doctor, date/time, location',completion:'Appointment outcome recorded'},
  'Appointment Completed':{roles:'Booking Administrator, Operations Manager, Medical Expert',required:'Attendance and outcome',completion:'Outcome and follow-up recorded'},
  'Documents Pending':{roles:'Booking Administrator, Operations Manager, File Preparation',required:'Document requirement / missing list',completion:'Required source documents received'},
  'File Preparation in Progress':{roles:'File Preparation, Operations Manager',required:'Source documents, preparer',completion:'Prepared bundle reviewed and approved'},
  'File Ready':{roles:'File Preparation, Medical Expert, Operations Manager',required:'Approved prepared bundle',completion:'File released to medical expert'},
  'Report in Progress':{roles:'Medical Expert, authorised report preparer',required:'Approved template and prepared case file',completion:'Draft report ready for QA submission'},
  'Draft Report Submitted':{roles:'Medical Expert, Quality Assurance',required:'Submitted report version, QA reviewer and due date',completion:'QA review started'},
  'QA Review':{roles:'Quality Assurance',required:'Submitted report version, checklist, reviewer',completion:'QA approve / amendment decision recorded'},
  'Amendments Required':{roles:'Medical Expert, Quality Assurance',required:'Recorded QA comments and required amendments',completion:'Amendments resolved and report resubmitted'},
  'Awaiting Final Approval':{roles:'Assigned Medical Expert',required:'QA approval',completion:'Final medical approval recorded'},
  'Final Report Approved':{roles:'Medical Expert, Booking Administrator, Operations Manager',required:'Doctor approval and declaration',completion:'Secure delivery recorded'},
  'Report Delivered':{roles:'Booking Administrator, Operations Manager',required:'Recipient, method, delivery date, final version',completion:'Outstanding required actions and tasks cleared'},
  'On Hold':{roles:'Booking Administrator, Operations Manager',required:'Hold reason, review date where known',completion:'Resume previous workflow status'},
  'Cancelled':{roles:'Booking Administrator, Operations Manager',required:'Cancellation reason',completion:'History retained; archive when appropriate'},
  'Completed':{roles:'Booking Administrator, Operations Manager',required:'Final delivery and no outstanding required work',completion:'Complete history retained for authorised users'},
  'Archived':{roles:'Booking Administrator, Operations Manager, System Administrator',required:'Closed case',completion:'Read-only retained record'},
}
const seedStatuses:CaseStatusRule[]=ALL_CASE_STATUSES.map((name,index)=>({
  id:`CS-${index+1}`,name,order:index+1,active:true,
  allowedNext:name==='On Hold'?'Resume previous workflow status':(ALLOWED_CASE_TRANSITIONS[name].join(', ')||'None'),
  rolePermissions:statusMeta[name]?.roles??'Operations Manager, System Administrator',
  requiredFields:statusMeta[name]?.required??'Workflow prerequisites',
  completionRules:statusMeta[name]?.completion??'Required workflow action completed',
}))
const seedAppointments:AppointmentTypeRule[]=[
  {id:'AT-1',name:'Initial Examination',duration:60,locationType:'Clinic / Remote',doctorEligibility:'Active medical experts',interpreterSupport:true,active:true},
  {id:'AT-2',name:'Follow-up Examination',duration:30,locationType:'Clinic / Remote',doctorEligibility:'Assigned doctor',interpreterSupport:true,active:true},
  {id:'AT-3',name:'Records Review',duration:45,locationType:'Remote',doctorEligibility:'Active medical experts',interpreterSupport:false,active:true},
]
const seedCategories:DocumentCategoryRule[]=[
  {id:'DC-1',name:'Client Instruction',order:1,requirement:'Required',aiRules:'Classification + instruction extraction',active:true},
  {id:'DC-2',name:'Medical Records',order:2,requirement:'Required',aiRules:'Classification + chronology/summary assistance',active:true},
  {id:'DC-3',name:'Prepared Bundle',order:6,requirement:'Generated',aiRules:'Human approval required before file-ready state',active:true},
]
const seedTemplates:ReportTemplate[]=[
  {id:'RT-1',name:'Standard Medicolegal Report',reportType:'Medicolegal',client:'All clients',caseType:'All case types',version:4,status:'Active',lastUpdated:'31 Aug 2026',fileName:'standard-medicolegal-v4.docx'},
  {id:'RT-2',name:'Addendum Report',reportType:'Addendum',client:'All clients',caseType:'All case types',version:2,status:'Active',lastUpdated:'28 Aug 2026',fileName:'addendum-v2.docx'},
  {id:'RT-3',name:'Condition & Prognosis Report',reportType:'Condition & Prognosis',client:'Selected clients',caseType:'Personal Injury — RTA',version:3,status:'Active',lastUpdated:'24 Aug 2026',fileName:'condition-prognosis-v3.docx'},
]
const seedChecklists:Checklist[]=[
  {id:'QC-1',name:'Standard QA Checklist',reportType:'Medicolegal',items:['Patient identity matches case','Instruction addressed','Opinion supported by evidence','Dates and chronology checked','Spelling and formatting checked'],requiredItems:['Patient identity matches case','Instruction addressed','Opinion supported by evidence','Dates and chronology checked'],severityOptions:['Low','Medium','High'],active:true},
  {id:'QC-2',name:'Clinical Negligence QA',reportType:'Clinical Negligence',items:['Identity verified','Breach opinion checked','Causation opinion checked','Source records cited','Declarations present'],requiredItems:['Identity verified','Breach opinion checked','Causation opinion checked','Declarations present'],severityOptions:['Low','Medium','High','Critical'],active:true},
]

function load<T>(key:string,fallback:T):T{try{const raw=localStorage.getItem(key);return raw?JSON.parse(raw) as T:fallback}catch{return fallback}}
function store<T>(key:string,value:T,setter:(value:T)=>void){setter(value);try{localStorage.setItem(key,JSON.stringify(value))}catch{/* prototype persistence only */}}

export default function AdminConfigurationWorkspaces(){
  const { showToast }=useToast()
  const [statuses,setStatuses]=useState(()=>load('evaluate-case-status-rules-v2-doc-prd',seedStatuses))
  const [appointments,setAppointments]=useState(()=>load('evaluate-appointment-type-rules-v1',seedAppointments))
  const [categories,setCategories]=useState(()=>load('evaluate-document-category-rules-v1',seedCategories))
  const [templates,setTemplates]=useState(()=>load('evaluate-report-templates-v1',seedTemplates))
  const [checklists,setChecklists]=useState(()=>load('evaluate-qa-checklists-v1',seedChecklists))
  const [statusEdit,setStatusEdit]=useState<CaseStatusRule|null>(null)
  const [appointmentEdit,setAppointmentEdit]=useState<AppointmentTypeRule|null>(null)
  const [categoryEdit,setCategoryEdit]=useState<DocumentCategoryRule|null>(null)
  const [templateEdit,setTemplateEdit]=useState<ReportTemplate|null>(null)
  const [checklistEdit,setChecklistEdit]=useState<Checklist|null>(null)

  const sortedStatuses=useMemo(()=>[...statuses].sort((a,b)=>a.order-b.order),[statuses])
  const sortedCategories=useMemo(()=>[...categories].sort((a,b)=>a.order-b.order),[categories])

  const saveStatus=(item:CaseStatusRule)=>{store('evaluate-case-status-rules-v2-doc-prd',statuses.some(x=>x.id===item.id)?statuses.map(x=>x.id===item.id?item:x):[...statuses,item],setStatuses);setStatusEdit(null);showToast('Case status configuration saved.')}
  const saveAppointment=(item:AppointmentTypeRule)=>{store('evaluate-appointment-type-rules-v1',appointments.some(x=>x.id===item.id)?appointments.map(x=>x.id===item.id?item:x):[...appointments,item],setAppointments);setAppointmentEdit(null);showToast('Appointment type configuration saved.')}
  const saveCategory=(item:DocumentCategoryRule)=>{store('evaluate-document-category-rules-v1',categories.some(x=>x.id===item.id)?categories.map(x=>x.id===item.id?item:x):[...categories,item],setCategories);setCategoryEdit(null);showToast('Document category configuration saved.')}
  const saveTemplate=(item:ReportTemplate)=>{store('evaluate-report-templates-v1',templates.some(x=>x.id===item.id)?templates.map(x=>x.id===item.id?item:x):[...templates,item],setTemplates);setTemplateEdit(null);showToast('Report template saved.')}
  const saveChecklist=(item:Checklist)=>{store('evaluate-qa-checklists-v1',checklists.some(x=>x.id===item.id)?checklists.map(x=>x.id===item.id?item:x):[...checklists,item],setChecklists);setChecklistEdit(null);showToast('QA checklist saved.')}

  return <div className="space-y-4">
    <ConfigTable title="Case status configuration" description="Status order, allowed transitions, permissions, required fields and completion rules." action="Add status" onAdd={()=>setStatusEdit({id:`CS-${Date.now()}`,name:'',order:sortedStatuses.length+1,active:true,allowedNext:'',rolePermissions:'',requiredFields:'',completionRules:''})} headers={['Status','Order','Allowed next','Role permissions','Required / completion','Status']} rows={sortedStatuses.map(item=>({id:item.id,cells:[item.name,String(item.order),item.allowedNext,item.rolePermissions,`${item.requiredFields} · ${item.completionRules}`,item.active?'Active':'Inactive'],onEdit:()=>setStatusEdit(item)}))}/>
    <ConfigTable title="Appointment type configuration" description="Duration, location type, doctor eligibility, interpreter support and active status." action="Add appointment type" onAdd={()=>setAppointmentEdit({id:`AT-${Date.now()}`,name:'',duration:30,locationType:'Clinic',doctorEligibility:'Active medical experts',interpreterSupport:true,active:true})} headers={['Appointment type','Duration','Location type','Doctor eligibility','Interpreter','Status']} rows={appointments.map(item=>({id:item.id,cells:[item.name,`${item.duration} min`,item.locationType,item.doctorEligibility,item.interpreterSupport?'Supported':'Not supported',item.active?'Active':'Inactive'],onEdit:()=>setAppointmentEdit(item)}))}/>
    <ConfigTable title="Document category configuration" description="Display order, requirement level, AI processing rules and active status." action="Add category" onAdd={()=>setCategoryEdit({id:`DC-${Date.now()}`,name:'',order:sortedCategories.length+1,requirement:'Optional',aiRules:'Manual review',active:true})} headers={['Category','Order','Required / optional','AI processing rules','Status']} rows={sortedCategories.map(item=>({id:item.id,cells:[item.name,String(item.order),item.requirement,item.aiRules,item.active?'Active':'Inactive'],onEdit:()=>setCategoryEdit(item)}))}/>

    <section className="bg-white border border-slate-200 rounded-xl overflow-hidden">
      <div className="px-4 py-3 border-b border-slate-100 flex flex-wrap items-center justify-between gap-3"><div><h3 className="text-sm font-semibold text-slate-900">Report template list & details</h3><p className="text-xs text-slate-500 mt-1">Upload/replace templates, create versions, assign client/case type and activate or deactivate.</p></div><button onClick={()=>setTemplateEdit({id:`RT-${Date.now()}`,name:'',reportType:'Medicolegal',client:'All clients',caseType:'All case types',version:1,status:'Active',lastUpdated:'Just now',fileName:''})} className="inline-flex items-center gap-1.5 rounded-lg bg-brand-600 px-3 py-2 text-xs font-medium text-white"><Plus size={14}/> Add template</button></div>
      <div className="overflow-x-auto"><table className="w-full min-w-[920px] text-xs"><thead><tr className="bg-slate-50 text-left text-[10px] uppercase tracking-wide text-slate-400"><th className="px-3 py-2">Template</th><th className="px-3 py-2">Report type</th><th className="px-3 py-2">Client</th><th className="px-3 py-2">Case type</th><th className="px-3 py-2">Version</th><th className="px-3 py-2">Status</th><th className="px-3 py-2">Last updated</th><th className="px-3 py-2 text-right">Actions</th></tr></thead><tbody className="divide-y divide-slate-100">{templates.map(t=><tr key={t.id}><td className="px-3 py-2.5 font-medium text-slate-700">{t.name}<p className="font-normal text-[10px] text-slate-400 mt-0.5">{t.fileName||'No file uploaded'}</p></td><td className="px-3 py-2.5 text-slate-600">{t.reportType}</td><td className="px-3 py-2.5 text-slate-600">{t.client}</td><td className="px-3 py-2.5 text-slate-600">{t.caseType}</td><td className="px-3 py-2.5 text-slate-600">v{t.version}</td><td className="px-3 py-2.5 text-slate-600">{t.status}</td><td className="px-3 py-2.5 text-slate-500">{t.lastUpdated}</td><td className="px-3 py-2.5"><div className="flex justify-end gap-1.5"><button onClick={()=>setTemplateEdit(t)} className="inline-flex items-center gap-1 rounded-md border px-2 py-1.5 text-brand-700"><Pencil size={12}/> Details</button><button onClick={()=>{const next={...t,version:t.version+1,lastUpdated:'Just now'};store('evaluate-report-templates-v1',templates.map(x=>x.id===t.id?next:x),setTemplates);showToast(`${t.name} version v${next.version} created.`)}} className="rounded-md border px-2 py-1.5 text-slate-600">New version</button><button onClick={()=>{const next={...t,status:(t.status==='Active'?'Inactive':'Active') as 'Active'|'Inactive',lastUpdated:'Just now'};store('evaluate-report-templates-v1',templates.map(x=>x.id===t.id?next:x),setTemplates);showToast(`${t.name} ${next.status.toLowerCase()}.`)}} className="rounded-md border px-2 py-1.5 text-slate-600"><Power size={12}/></button></div></td></tr>)}</tbody></table></div>
    </section>

    <section className="bg-white border border-slate-200 rounded-xl overflow-hidden">
      <div className="px-4 py-3 border-b border-slate-100 flex flex-wrap items-center justify-between gap-3"><div><h3 className="text-sm font-semibold text-slate-900">QA checklist management</h3><p className="text-xs text-slate-500 mt-1">Manage checklist items, required items, severity options, report type and active status.</p></div><button onClick={()=>setChecklistEdit({id:`QC-${Date.now()}`,name:'',reportType:'Medicolegal',items:['New checklist item'],requiredItems:['New checklist item'],severityOptions:['Low','Medium','High'],active:true})} className="inline-flex items-center gap-1.5 rounded-lg bg-brand-600 px-3 py-2 text-xs font-medium text-white"><Plus size={14}/> Add checklist</button></div>
      <div className="divide-y divide-slate-100">{checklists.map(c=><div key={c.id} className="p-4 flex flex-col md:flex-row md:items-center justify-between gap-3"><div><div className="flex items-center gap-2"><CheckCircle2 size={15} className="text-brand-600"/><p className="text-sm font-semibold text-slate-800">{c.name}</p><span className={`rounded-full px-2 py-0.5 text-[10px] ${c.active?'bg-teal-50 text-teal-700':'bg-slate-100 text-slate-500'}`}>{c.active?'Active':'Inactive'}</span></div><p className="text-xs text-slate-500 mt-1">{c.reportType} · {c.items.length} items · {c.requiredItems.length} required · Severity: {c.severityOptions.join(' / ')}</p></div><button onClick={()=>setChecklistEdit(c)} className="inline-flex items-center gap-1.5 self-start md:self-auto rounded-lg border border-slate-200 px-3 py-2 text-xs font-medium text-brand-700"><Pencil size={13}/> Manage checklist</button></div>)}</div>
    </section>

    {statusEdit&&<CaseStatusModal value={statusEdit} onClose={()=>setStatusEdit(null)} onSave={saveStatus}/>} 
    {appointmentEdit&&<AppointmentTypeModal value={appointmentEdit} onClose={()=>setAppointmentEdit(null)} onSave={saveAppointment}/>} 
    {categoryEdit&&<DocumentCategoryModal value={categoryEdit} onClose={()=>setCategoryEdit(null)} onSave={saveCategory}/>} 
    {templateEdit&&<ReportTemplateModal value={templateEdit} onClose={()=>setTemplateEdit(null)} onSave={saveTemplate}/>} 
    {checklistEdit&&<ChecklistModal value={checklistEdit} onClose={()=>setChecklistEdit(null)} onSave={saveChecklist}/>} 
  </div>
}

function ConfigTable({title,description,action,onAdd,headers,rows}:{title:string;description:string;action:string;onAdd:()=>void;headers:string[];rows:{id:string;cells:string[];onEdit:()=>void}[]}){
  return <section className="bg-white border border-slate-200 rounded-xl overflow-hidden"><div className="px-4 py-3 border-b border-slate-100 flex flex-wrap items-center justify-between gap-3"><div><h3 className="text-sm font-semibold text-slate-900">{title}</h3><p className="text-xs text-slate-500 mt-1">{description}</p></div><button onClick={onAdd} className="inline-flex items-center gap-1.5 rounded-lg border border-brand-200 bg-brand-50 px-3 py-2 text-xs font-medium text-brand-700"><Plus size={14}/>{action}</button></div><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-xs"><thead><tr className="bg-slate-50 text-left text-[10px] uppercase tracking-wide text-slate-400">{headers.map(h=><th key={h} className="px-3 py-2">{h}</th>)}<th className="px-3 py-2 text-right">Action</th></tr></thead><tbody className="divide-y divide-slate-100">{rows.map(row=><tr key={row.id}>{row.cells.map((cell,i)=><td key={i} className={`px-3 py-2.5 ${i===0?'font-medium text-slate-700':'text-slate-600'} max-w-[260px]`}>{cell}</td>)}<td className="px-3 py-2.5 text-right"><button onClick={row.onEdit} className="inline-flex items-center gap-1 rounded-md border border-slate-200 px-2 py-1.5 text-brand-700"><Pencil size={12}/> Edit</button></td></tr>)}</tbody></table></div></section>
}

function CaseStatusModal({value,onClose,onSave}:{value:CaseStatusRule;onClose:()=>void;onSave:(v:CaseStatusRule)=>void}){const [v,setV]=useState(value);return <Modal title="Case status configuration" description="Define status order, allowed next statuses, role permissions, required fields and completion rules." onClose={onClose} width="max-w-2xl"><div className="grid sm:grid-cols-2 gap-3"><Text labelText="Status name" value={v.name} onChange={x=>setV({...v,name:x})}/><NumberField labelText="Status order" value={v.order} onChange={x=>setV({...v,order:x})}/><Text labelText="Allowed next statuses" value={v.allowedNext} onChange={x=>setV({...v,allowedNext:x})}/><Text labelText="Role permissions" value={v.rolePermissions} onChange={x=>setV({...v,rolePermissions:x})}/><Text labelText="Required fields" value={v.requiredFields} onChange={x=>setV({...v,requiredFields:x})}/><Text labelText="Completion rules" value={v.completionRules} onChange={x=>setV({...v,completionRules:x})}/><Toggle labelText="Active status" checked={v.active} onChange={x=>setV({...v,active:x})}/></div><ModalActions onClose={onClose} onSave={()=>v.name.trim()&&onSave(v)}/></Modal>}
function AppointmentTypeModal({value,onClose,onSave}:{value:AppointmentTypeRule;onClose:()=>void;onSave:(v:AppointmentTypeRule)=>void}){const [v,setV]=useState(value);return <Modal title="Appointment type configuration" description="Configure duration, location type, doctor eligibility, interpreter support and status." onClose={onClose} width="max-w-2xl"><div className="grid sm:grid-cols-2 gap-3"><Text labelText="Appointment name" value={v.name} onChange={x=>setV({...v,name:x})}/><NumberField labelText="Duration (minutes)" value={v.duration} onChange={x=>setV({...v,duration:x})}/><Text labelText="Location type" value={v.locationType} onChange={x=>setV({...v,locationType:x})}/><Text labelText="Doctor eligibility" value={v.doctorEligibility} onChange={x=>setV({...v,doctorEligibility:x})}/><Toggle labelText="Interpreter support" checked={v.interpreterSupport} onChange={x=>setV({...v,interpreterSupport:x})}/><Toggle labelText="Active status" checked={v.active} onChange={x=>setV({...v,active:x})}/></div><ModalActions onClose={onClose} onSave={()=>v.name.trim()&&onSave(v)}/></Modal>}
function DocumentCategoryModal({value,onClose,onSave}:{value:DocumentCategoryRule;onClose:()=>void;onSave:(v:DocumentCategoryRule)=>void}){const [v,setV]=useState(value);return <Modal title="Document category configuration" description="Configure display order, requirement, AI processing rules and active status." onClose={onClose} width="max-w-2xl"><div className="grid sm:grid-cols-2 gap-3"><Text labelText="Category name" value={v.name} onChange={x=>setV({...v,name:x})}/><NumberField labelText="Display order" value={v.order} onChange={x=>setV({...v,order:x})}/><div><label className={label}>Required or optional</label><select className={field} value={v.requirement} onChange={e=>setV({...v,requirement:e.target.value as DocumentCategoryRule['requirement']})}><option>Required</option><option>Optional</option><option>Generated</option></select></div><Text labelText="AI processing rules" value={v.aiRules} onChange={x=>setV({...v,aiRules:x})}/><Toggle labelText="Active status" checked={v.active} onChange={x=>setV({...v,active:x})}/></div><ModalActions onClose={onClose} onSave={()=>v.name.trim()&&onSave(v)}/></Modal>}
function ReportTemplateModal({value,onClose,onSave}:{value:ReportTemplate;onClose:()=>void;onSave:(v:ReportTemplate)=>void}){const [v,setV]=useState(value);const upload=(replace=false)=>{const file=window.prompt(replace?'Enter replacement template filename':'Enter uploaded template filename',v.fileName||'report-template.docx');if(file)setV({...v,fileName:file,lastUpdated:'Just now'})};return <Modal title="Report template details" description="Template version, assignments and activation controls." onClose={onClose} width="max-w-2xl"><div className="grid sm:grid-cols-2 gap-3"><Text labelText="Template name" value={v.name} onChange={x=>setV({...v,name:x})}/><Text labelText="Report type" value={v.reportType} onChange={x=>setV({...v,reportType:x})}/><Text labelText="Assigned client" value={v.client} onChange={x=>setV({...v,client:x})}/><Text labelText="Assigned case type" value={v.caseType} onChange={x=>setV({...v,caseType:x})}/><NumberField labelText="Version" value={v.version} onChange={x=>setV({...v,version:x})}/><div><label className={label}>Status</label><select className={field} value={v.status} onChange={e=>setV({...v,status:e.target.value as 'Active'|'Inactive'})}><option>Active</option><option>Inactive</option></select></div></div><div className="mt-4 rounded-lg border border-slate-200 p-3"><p className={label}>Template file</p><div className="flex flex-wrap items-center justify-between gap-2"><div className="flex items-center gap-2 text-xs text-slate-600"><FileText size={15}/>{v.fileName||'No file uploaded'}</div><div className="flex gap-2"><button onClick={()=>upload(false)} className="inline-flex items-center gap-1 rounded-md border px-2.5 py-1.5 text-xs"><Upload size={12}/> Upload template</button><button onClick={()=>upload(true)} className="rounded-md border px-2.5 py-1.5 text-xs">Replace template</button><button onClick={()=>setV({...v,version:v.version+1,lastUpdated:'Just now'})} className="rounded-md border px-2.5 py-1.5 text-xs">Create new version</button></div></div></div><ModalActions onClose={onClose} onSave={()=>v.name.trim()&&onSave({...v,lastUpdated:'Just now'})}/></Modal>}
function ChecklistModal({value,onClose,onSave}:{value:Checklist;onClose:()=>void;onSave:(v:Checklist)=>void}){const [v,setV]=useState(value);const [newItem,setNewItem]=useState('');const [newSeverity,setNewSeverity]=useState('');return <Modal title="QA checklist management" description="Edit checklist items, required flags, severity options and active status." onClose={onClose} width="max-w-3xl"><div className="grid sm:grid-cols-2 gap-3"><Text labelText="Checklist name" value={v.name} onChange={x=>setV({...v,name:x})}/><Text labelText="Report type" value={v.reportType} onChange={x=>setV({...v,reportType:x})}/><Toggle labelText="Active status" checked={v.active} onChange={x=>setV({...v,active:x})}/></div><div className="mt-4"><p className={label}>Checklist items</p><div className="rounded-lg border border-slate-200 divide-y divide-slate-100">{v.items.map(item=><div key={item} className="flex items-center gap-3 px-3 py-2"><input type="checkbox" checked={v.requiredItems.includes(item)} onChange={()=>setV({...v,requiredItems:v.requiredItems.includes(item)?v.requiredItems.filter(x=>x!==item):[...v.requiredItems,item]})}/><span className="flex-1 text-xs text-slate-700">{item}</span><span className="text-[10px] text-slate-400">{v.requiredItems.includes(item)?'Required':'Optional'}</span><button onClick={()=>setV({...v,items:v.items.filter(x=>x!==item),requiredItems:v.requiredItems.filter(x=>x!==item)})} className="text-xs text-red-500">Remove</button></div>)}</div><div className="flex gap-2 mt-2"><input className={field} value={newItem} onChange={e=>setNewItem(e.target.value)} placeholder="Add checklist item"/><button onClick={()=>{const clean=newItem.trim();if(clean&&!v.items.includes(clean)){setV({...v,items:[...v.items,clean]});setNewItem('')}}} className="rounded-lg bg-brand-600 px-3 text-white"><Plus size={14}/></button></div></div><div className="mt-4"><p className={label}>Severity options</p><div className="flex flex-wrap gap-2">{v.severityOptions.map(s=><button key={s} onClick={()=>setV({...v,severityOptions:v.severityOptions.filter(x=>x!==s)})} className="rounded-full border px-2.5 py-1 text-xs text-slate-600">{s} ×</button>)}</div><div className="flex gap-2 mt-2"><input className={field} value={newSeverity} onChange={e=>setNewSeverity(e.target.value)} placeholder="Add severity option"/><button onClick={()=>{const clean=newSeverity.trim();if(clean&&!v.severityOptions.includes(clean)){setV({...v,severityOptions:[...v.severityOptions,clean]});setNewSeverity('')}}} className="rounded-lg border px-3 text-xs">Add</button></div></div><ModalActions onClose={onClose} onSave={()=>v.name.trim()&&v.items.length>0&&onSave(v)}/></Modal>}

function Text({labelText,value,onChange}:{labelText:string;value:string;onChange:(v:string)=>void}){return <div><label className={label}>{labelText}</label><input className={field} value={value} onChange={e=>onChange(e.target.value)}/></div>}
function NumberField({labelText,value,onChange}:{labelText:string;value:number;onChange:(v:number)=>void}){return <div><label className={label}>{labelText}</label><input type="number" min="1" className={field} value={value} onChange={e=>onChange(Number(e.target.value)||1)}/></div>}
function Toggle({labelText,checked,onChange}:{labelText:string;checked:boolean;onChange:(v:boolean)=>void}){return <label className="flex items-center gap-2 self-end min-h-[40px] rounded-lg border border-slate-200 px-3 text-xs text-slate-700"><input type="checkbox" checked={checked} onChange={e=>onChange(e.target.checked)}/>{labelText}</label>}
function ModalActions({onClose,onSave}:{onClose:()=>void;onSave:()=>void}){return <div className="mt-5 flex justify-end gap-2 border-t border-slate-100 pt-4"><button onClick={onClose} className="rounded-lg border border-slate-200 px-3 py-2 text-sm text-slate-600">Cancel</button><button onClick={onSave} className="rounded-lg bg-brand-600 px-4 py-2 text-sm font-medium text-white">Save configuration</button></div>}
