import { useState } from 'react'
import Modal from './Modal'
import PhoneInput from './PhoneInput'
import type { Doctor } from '../types'

const field='w-full border border-slate-200 rounded-lg px-3 py-2 text-sm text-slate-700 focus:outline-none focus:ring-2 focus:ring-brand-500/30 focus:border-brand-500'
const label='block text-xs font-medium text-slate-500 mb-1.5'
const locationOptions=['Manchester Clinic','Leeds Clinic','London Clinic','Remote — Video']
const appointmentOptions=['Initial Examination','Follow-up Examination','Video Consultation','Records Review']
const templateOptions=['Standard Medicolegal Report','Personal Injury Report','Psychiatric Report','Addendum Report']

export default function EditDoctorModal({doctor,onClose,onSave}:{doctor:Doctor;onClose:()=>void;onSave:(doctor:Doctor)=>void}){
  const [draft,setDraft]=useState<Doctor>({...doctor, locations:doctor.locations??[doctor.location], appointmentTypes:doctor.appointmentTypes??[], reportTemplates:doctor.reportTemplates??[]})
  const [error,setError]=useState('')
  const update=<K extends keyof Doctor>(key:K,value:Doctor[K])=>{setDraft(prev=>({...prev,[key]:value}));setError('')}
  const toggle=(key:'locations'|'appointmentTypes'|'reportTemplates',value:string)=>{const current=(draft[key]??[]) as string[];update(key,(current.includes(value)?current.filter(x=>x!==value):[...current,value]) as Doctor[typeof key])}
  const save=()=>{if(!draft.name.trim()||!draft.speciality.trim())return setError('Doctor name and speciality are required.');if(draft.email&& !/^\S+@\S+\.\S+$/.test(draft.email))return setError('Enter a valid email address.');if(draft.phone&&draft.phone.replace(/\D/g,'').length<7)return setError('Enter a valid phone number.');if(!(draft.locations??[]).length)return setError('Select at least one location.');if(!(draft.appointmentTypes??[]).length)return setError('Select at least one appointment type.');onSave({...draft,name:draft.name.trim(),speciality:draft.speciality.trim(),professionalDetails:`${draft.speciality.trim()} · ${draft.qualifications?.trim()||'Medical expert panel member'}`})}
  return <Modal title="Edit doctor" description={`${doctor.id} · Professional, availability and report settings.`} onClose={onClose} width="max-w-4xl"><div className="space-y-5">{error&&<p className="text-xs text-red-600 bg-red-50 border border-red-100 rounded-lg px-3 py-2">{error}</p>}
    <section><p className="text-xs font-semibold uppercase tracking-wide text-slate-400 mb-3">Professional details</p><div className="grid sm:grid-cols-2 gap-3"><div><label className={label}>Name *</label><input className={field} value={draft.name} onChange={e=>update('name',e.target.value)}/></div><div><label className={label}>Speciality *</label><input className={field} value={draft.speciality} onChange={e=>update('speciality',e.target.value)}/></div><div className="sm:col-span-2"><label className={label}>Qualifications</label><textarea className={field} rows={2} value={draft.qualifications??''} onChange={e=>update('qualifications',e.target.value)}/></div><div><label className={label}>Email</label><input type="email" className={field} value={draft.email??''} onChange={e=>update('email',e.target.value)}/></div><div><label className={label}>Phone</label><PhoneInput value={draft.phone??''} onChange={v=>update('phone',v)}/></div></div></section>
    <section className="border-t border-slate-100 pt-4"><p className="text-xs font-semibold uppercase tracking-wide text-slate-400 mb-3">Assignment settings</p><div className="grid sm:grid-cols-2 gap-3"><div><label className={label}>Primary location</label><select className={field} value={draft.location} onChange={e=>update('location',e.target.value)}>{locationOptions.map(x=><option key={x}>{x}</option>)}</select></div><div><label className={label}>Availability</label><select className={field} value={draft.availability} onChange={e=>update('availability',e.target.value as Doctor['availability'])}><option>Available</option><option>Limited Availability</option><option>Fully Booked</option><option>On Leave</option></select></div></div><div className="mt-3"><label className={label}>Locations</label><div className="flex flex-wrap gap-2">{locationOptions.map(x=><button type="button" key={x} onClick={()=>toggle('locations',x)} className={`text-xs px-3 py-1.5 rounded-full border ${(draft.locations??[]).includes(x)?'bg-brand-50 border-brand-500 text-brand-700 font-medium':'border-slate-200 text-slate-500'}`}>{x}</button>)}</div></div><div className="mt-3"><label className={label}>Appointment types</label><div className="flex flex-wrap gap-2">{appointmentOptions.map(x=><button type="button" key={x} onClick={()=>toggle('appointmentTypes',x)} className={`text-xs px-3 py-1.5 rounded-full border ${(draft.appointmentTypes??[]).includes(x)?'bg-brand-50 border-brand-500 text-brand-700 font-medium':'border-slate-200 text-slate-500'}`}>{x}</button>)}</div></div></section>
    <section className="border-t border-slate-100 pt-4"><p className="text-xs font-semibold uppercase tracking-wide text-slate-400 mb-3">Availability settings</p><div className="grid sm:grid-cols-2 gap-3"><div><label className={label}>Weekly availability</label><input className={field} value={draft.weeklyAvailability??''} onChange={e=>update('weeklyAvailability',e.target.value)}/></div><div><label className={label}>Available hours</label><input className={field} value={draft.availableHours??''} onChange={e=>update('availableHours',e.target.value)}/></div><div><label className={label}>Blocked periods</label><textarea className={field} rows={2} value={draft.blockedPeriods??''} onChange={e=>update('blockedPeriods',e.target.value)}/></div><div><label className={label}>Leave</label><textarea className={field} rows={2} value={draft.leaveDetails??''} onChange={e=>update('leaveDetails',e.target.value)}/></div><div className="sm:col-span-2"><label className={label}>Availability notes</label><textarea className={field} rows={2} value={draft.availabilityNotes??''} onChange={e=>update('availabilityNotes',e.target.value)}/></div></div></section>
    <section className="border-t border-slate-100 pt-4"><p className="text-xs font-semibold uppercase tracking-wide text-slate-400 mb-3">Reports & fees</p><label className={label}>Report templates</label><div className="flex flex-wrap gap-2">{templateOptions.map(x=><button type="button" key={x} onClick={()=>toggle('reportTemplates',x)} className={`text-xs px-3 py-1.5 rounded-full border ${(draft.reportTemplates??[]).includes(x)?'bg-brand-50 border-brand-500 text-brand-700 font-medium':'border-slate-200 text-slate-500'}`}>{x}</button>)}</div><div className="mt-3"><label className={label}>Standard fees</label><input className={field} value={draft.standardFees??''} onChange={e=>update('standardFees',e.target.value)}/></div></section>
  </div><div className="flex justify-end gap-2 mt-5 pt-4 border-t border-slate-100"><button onClick={onClose} className="px-4 py-2 text-sm font-medium text-slate-600 hover:bg-slate-50 rounded-lg">Cancel</button><button onClick={save} className="px-4 py-2 text-sm font-medium text-white bg-brand-600 hover:bg-brand-700 rounded-lg">Save doctor</button></div></Modal>
}
